version: 2.1

setup: true

orbs:
  git-submodule-changes: butterflynetwork/git-submodule-changes@0.2.2

workflows:
  generate-config:
    jobs:
      - git-submodule-changes/continue-with-changed:
          config-path: .circleci/continue-config.yml