version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  project-one:
    type: boolean
    default: false
  project-two:
    type: boolean
    default: false

jobs:
  project_one:
    executor: base
    steps:
      - run:
          name: project-one
          command: |
            echo 'project-one'

  project_two:
    executor: base
    steps:
      - run:
          name: project-two
          command: |
            echo 'project-two'

workflows:
  project-one:
    when: << pipeline.parameters.project-one >>
    jobs:
      - project_one
  project-two:
    when: << pipeline.parameters.project-two >>
    jobs:
      - project_two